// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product_writer_messages.proto

package writerService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=Price,proto3" json:"Price,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	DeletedAt            string   `protobuf:"bytes,8,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fbb9e3ccb81915a, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Product) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Product) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type CreateProductReq struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=Price,proto3" json:"Price,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	DeletedAt            string   `protobuf:"bytes,8,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductReq) Reset()         { *m = CreateProductReq{} }
func (m *CreateProductReq) String() string { return proto.CompactTextString(m) }
func (*CreateProductReq) ProtoMessage()    {}
func (*CreateProductReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fbb9e3ccb81915a, []int{1}
}

func (m *CreateProductReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductReq.Unmarshal(m, b)
}
func (m *CreateProductReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductReq.Marshal(b, m, deterministic)
}
func (m *CreateProductReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductReq.Merge(m, src)
}
func (m *CreateProductReq) XXX_Size() int {
	return xxx_messageInfo_CreateProductReq.Size(m)
}
func (m *CreateProductReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductReq proto.InternalMessageInfo

func (m *CreateProductReq) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *CreateProductReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProductReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateProductReq) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CreateProductReq) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *CreateProductReq) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *CreateProductReq) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type CreateProductRes struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductRes) Reset()         { *m = CreateProductRes{} }
func (m *CreateProductRes) String() string { return proto.CompactTextString(m) }
func (*CreateProductRes) ProtoMessage()    {}
func (*CreateProductRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fbb9e3ccb81915a, []int{2}
}

func (m *CreateProductRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRes.Unmarshal(m, b)
}
func (m *CreateProductRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRes.Marshal(b, m, deterministic)
}
func (m *CreateProductRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRes.Merge(m, src)
}
func (m *CreateProductRes) XXX_Size() int {
	return xxx_messageInfo_CreateProductRes.Size(m)
}
func (m *CreateProductRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRes proto.InternalMessageInfo

func (m *CreateProductRes) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "writerService.Product")
	proto.RegisterType((*CreateProductReq)(nil), "writerService.CreateProductReq")
	proto.RegisterType((*CreateProductRes)(nil), "writerService.CreateProductRes")
}

func init() { proto.RegisterFile("product_writer_messages.proto", fileDescriptor_9fbb9e3ccb81915a) }

var fileDescriptor_9fbb9e3ccb81915a = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x4f,
	0x29, 0x4d, 0x2e, 0x89, 0x2f, 0x2f, 0xca, 0x2c, 0x49, 0x2d, 0x8a, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e,
	0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x85, 0x08, 0x07, 0xa7, 0x16,
	0x95, 0x65, 0x26, 0xa7, 0x2a, 0x9d, 0x65, 0xe4, 0x62, 0x0f, 0x80, 0x68, 0x10, 0x92, 0xe1, 0xe2,
	0x84, 0x32, 0x3d, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x10, 0x02, 0x42, 0x42, 0x5c,
	0x2c, 0x7e, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x60, 0x09, 0x30, 0x5b, 0x48, 0x81, 0x8b, 0xdb, 0x25,
	0xb5, 0x38, 0xb9, 0x28, 0xb3, 0xa0, 0x24, 0x33, 0x3f, 0x4f, 0x82, 0x19, 0x2c, 0x85, 0x2c, 0x24,
	0x24, 0xc2, 0xc5, 0x1a, 0x50, 0x94, 0x99, 0x9c, 0x2a, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x18, 0x04,
	0xe1, 0x80, 0x6c, 0x72, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x4d, 0x71, 0x2c, 0x91, 0x60, 0x83, 0xd8,
	0x04, 0x17, 0x00, 0xc9, 0x86, 0x16, 0xa4, 0x40, 0x65, 0xd9, 0x21, 0xb2, 0x70, 0x01, 0x90, 0xac,
	0x4b, 0x6a, 0x4e, 0x2a, 0x44, 0x96, 0x03, 0x22, 0x0b, 0x17, 0x50, 0xba, 0xc6, 0xc8, 0x25, 0x00,
	0x31, 0x09, 0xea, 0xf2, 0xa0, 0xd4, 0xc2, 0x61, 0xe1, 0x31, 0x03, 0x0c, 0x7f, 0x15, 0xe3, 0xf7,
	0x97, 0x93, 0x50, 0x94, 0x80, 0x9e, 0xbe, 0x35, 0x4a, 0x74, 0x27, 0xb1, 0x81, 0x13, 0x81, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xd6, 0x6c, 0x50, 0x25, 0x02, 0x00, 0x00,
}
