serviceName: writer_service
grpc:
  readerServicePort: 5003
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbName: products
  sslMode: false
kafka:
  brokers: [ "localhost:9092" ]
  groupID: product_core_writer_api_consumer
  initTopics: true
kafkaTopics:
  productCreate:
    topicName: product_create
    partitions: 10
    replicationFactor: 1
  productDelete:
    topicName: product_delete
    partitions: 10
    replicationFactor: 1
  productDeactivate:
    topicName: product_deactivate
    partitions: 10
    replicationFactor: 1
  productUpdate:
    topicName: product_update
    partitions: 2
    replicationFactor: 1